# Generated by Django 5.0.1 on 2024-02-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_orderitem_order_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custom',
            new_name='customer',
        ),
    ]
