# Generated by Django 5.0.1 on 2024-02-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productratting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productratting',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='productratting',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductRatting',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
