# Generated by Django 5.0.1 on 2024-02-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='deleted_at',
        ),
    ]
