# Generated by Django 5.0.1 on 2024-02-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_productratting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rawitem',
            name='deleted_at',
        ),
    ]
