# Generated by Django 5.0.1 on 2024-02-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
