# Generated by Django 5.0.1 on 2024-02-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_fooditem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='tags',
        ),
    ]
