# Generated by Django 5.0.1 on 2024-02-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='deleted_at',
        ),
    ]
