# Generated by Django 5.0.1 on 2024-02-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Redirect to bank', 'Redirect To Bank'), ('Return from bank', 'Return From Bank'), ('Cancel by user', 'Cancel By User'), ('Expire gateway token', 'Expire Gateway Token'), ('Expire verify payment', 'Expire Verify Payment'), ('Complete', 'Complete'), ('Unknown error acquired', 'Error')], max_length=50, verbose_name='Status')),
                ('bank_type', models.CharField(choices=[('ZARINPAL', 'Zarinpal')], max_length=50, verbose_name='Bank')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='Tracking code')),
                ('amount', models.CharField(max_length=10, verbose_name='Amount')),
                ('reference_number', models.CharField(max_length=255, unique=True, verbose_name='Reference number')),
                ('response_result', models.TextField(blank=True, null=True, verbose_name='Bank result')),
                ('callback_url', models.TextField(verbose_name='Callback url')),
                ('extra_information', models.TextField(blank=True, null=True, verbose_name='Extra information')),
                ('bank_choose_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank choose identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Bank gateway',
                'verbose_name_plural': 'Bank gateways',
            },
        ),
    ]
