# Generated by Django 5.0.1 on 2024-02-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/cover_photos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/profile_picture'),
        ),
    ]
