# Generated by Django 5.0.1 on 2024-02-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_token',
            new_name='otp',
        ),
    ]
