# Generated by Django 5.0.1 on 2024-02-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_email_verification_token_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
