# Generated by Django 5.0.1 on 2024-02-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_otp_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_otp_sent',
        ),
    ]
