# Generated by Django 5.0.1 on 2024-02-27 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_token_valid_from_user_token_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 14, 14, 57, 675388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 14, 19, 57, 675388, tzinfo=datetime.timezone.utc)),
        ),
    ]
