# Generated by Django 5.0.1 on 2024-02-27 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_token_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 20, 2, 51, 795205, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 20, 7, 51, 795205, tzinfo=datetime.timezone.utc)),
        ),
    ]
