# Generated by Django 5.0.1 on 2024-02-27 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_token_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 20, 3, 51, 897564, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 20, 8, 51, 898567, tzinfo=datetime.timezone.utc)),
        ),
    ]
