# Generated by Django 5.0.1 on 2024-03-04 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_token_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 13, 42, 10, 640555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 13, 47, 10, 640555, tzinfo=datetime.timezone.utc)),
        ),
    ]
